### ISSUE TITLE
Ajax not working Properly

### ISSUE THREAD

**Issue by merilturock** [hypeJunction/hypeInteractions#1]
Dear Ismayil,
        This error is really weird the hypeinteraction works when i activate any plugin are when i Login again it works perfectly but after my login if i navigate to my website & try to click the comment this is what it looks like
![hypeinteraction](https://cloud.githubusercontent.com/assets/1689530/6430406/dbc7929a-c02e-11e4-932f-a8aa88a3fae1.PNG)
 
I tried deactivating all the third party plugin & still i have the same problem. Can you advise me why i am facing this problem. 
Thanks for this wonderful plugin it really gives a rich look for elgg.

Thanks & Regards
Meril

**Comment by hypeJunction** [comment]
I don't see the issue. Can  you try latest release and reopen if you still see the issue.
