### ISSUE TITLE
Some troubles hypeInteractions

### ISSUE THREAD

**Issue by rheman** [hypeJunction/hypeInteractions#15]
Hi everyone I am using hypeInteractions 5.3.1 and I have some troubles with the like action button. 

Everytime a user click on like button, the action is performed but the user is redirected to the https://xxxxxxx/stream/stream/likes/12356&nbsp; and the page is refreshed. So  I commented out forward("stream/likes/$entity->guid"); located in mod/hypeInteractions/actions/likes/add.php. But when the user click on like button, the action is performed but the page is still refreshed .  

How can I solve this issue ?

Best regard.

**Comment by hypeJunction** [comment]
You have some client side error. Open the browser console and see if you can capture what's happening when you click and why the default action is not prevented. My guess another plugin errors and terminates JS execution

**Comment by rheman** [comment]
Thanks a lot I tried to check what's wrong using firefox javascript console. But no error is displayed on console when I click on like button....

**Comment by rheman** [comment]
Could someone help me.  I try for my best but I still dont know what's is wrong. I am using the lastest hypeInteractions plugin under SocialApparatus Twitter® Bootstrap Theme (https://elgg.org/plugins/2657288)
Need help.
Best regard

**Comment by hypeJunction** [comment]
I am quite the problem is with the theme's JavaScript. Can't help you if that is the case

**Comment by rheman** [comment]
Thanks...

**Comment by rheman** [comment]
I have disable all theme js then fush cache but still have the same problem.

**Comment by hypeJunction** [comment]
Keep disabling the plugins until you find the one that breaks it

**Comment by rheman** [comment]
Thanks a lot. I did it

**Comment by hypeJunction** [comment]
What was it?

**Comment by rheman** [comment]
It was due to css code. On the socia_bootstrap_theme available here https://elgg.org/plugins/2657288

the css file has the following entries

If (!elgg_in_context("admin")) {

    $vars['class'] = str_replace("elgg-button", "btn", $vars['class']);
    $vars['class'] = str_replace("delete", "danger", $vars['class']);
    $vars['class'] = str_replace("float-alt", "pull-right", $vars['class']);
    $vars['class'] = str_replace("action", "info", $vars['class']);
    $vars['class'] = str_replace("submit", "success", $vars['class']);
    $vars['class'] = str_replace("cancel", "warning", $vars['class']);
}

The problem was caused by the above code.
