### ISSUE TITLE
HypeLists don't load before Ajax on full view

### ISSUE THREAD

**Issue by DavidLycaweb** [hypeJunction/hypeInteractions#2]
Hi Ismayil, I'm David from Elgg.org, I have this issue: the JS don't load after Ajax query on full view. On activity river the JS loads perfectly after Ajax, but in full view don't. I think if I could make comments loaded with content, JS would load properly. It's a theory.

Thanks!

**Comment by merilturock** [comment]
I am also facing the same problem.

**Comment by hypeJunction** [comment]
Should be fixed with latest hypeLists
