### ISSUE TITLE
Reply text form should not be displayed, because of the "Comment tree depth" setting

### ISSUE THREAD

**Issue by oseg** [hypeJunction/hypeInteractions#5]
**Issue**: Reply text form should not be displayed, because of the "Comment tree depth" setting
**Context**: elgg core v1.12.9, latest version of hypeinteraction 3.X branch (commit #45b1a16) with "Comment tree depth" plugin setting set to "2"
**Scenario**:
- "usertest" create a bookmark
- "Olivier" comment this bookmark: "thanks for this bookmark"
- "Admin" reply to "Olivier" 's comment: "I agree, great bookmark"
- "Olivier" adds another comment: "test comment"
- "Admin" adds a 3rd comment: "test admin comment" 

When any user ("Olivier", "usertest" or another user except "admin") visit this bookmark page, a non empty text form is displayed just after "admin" 's reply "I agree, great bookmark", with the content of the previous reply inside it: "I agree great bookmark" (see screenshot below)

![hypeinteraction-ui-bug](https://cloud.githubusercontent.com/assets/15892521/16072224/10c871c4-32e0-11e6-93de-fbdad3721530.jpg)
- This text form should not be displayed, because of the plugin settings set to 2

Pressing the "reply" button results in a "You are unauthorized to perform this action" message

**Comment by hypeJunction** [comment]
I am quite sure it's fixed in the 4.x branch. I don't have any more project left using Elgg 1.12, so it's not worth my time hunting this down.
