### ISSUE TITLE
How can i disable "Like" for wire posts and "comment" on messageboard posts in river activity?

### ISSUE THREAD

**Issue by DaveONchE** [hypeJunction/hypeInteractions#7]
Hello Ismayil,
I noticed likes on wire posts and comments on messageboard posts creates a river notification in river activity which only gives the raw url link to the posts being liked or commented on. I guess these is happening because thewire and messageboard plugins were not designed to get likes and comments. 
So, i am trying to disable hypeInteractions on only thewire and messageboard posts in river activity as a possible solution. How may I achieve this? Thanks.

Dave.

**Comment by hypeJunction** [comment]
You can use hooks to return false likes:is_likeable

**Comment by DaveONchE** [comment]
Ok... but that seem to only work on thewire posts. Here is what i used:

elgg_register_plugin_hook_handler('likes:is_likable', 'object:thewire', 'Elgg\Values::getFalse');

How can i do this for comments on messageboard river post?

Thank you.

**Comment by hypeJunction** [comment]
permissions_check:comment hook. It's all in the Elgg docs
