### ISSUE TITLE
WARNING: Deprecated in 2.3: elgg_view_input() is deprecated. Use elgg_view_field() 

### ISSUE THREAD

**Issue by egbayram** [hypeJunction/hypeInteractions#9]
Hi I receive a warning like this below the user comment box.

**Comment by egbayram** [comment]
WARNING: Deprecated in 2.3: elgg_view_input() is deprecated. Use elgg_view_field() Called from [#61] /var/www/elgg/vendor/elgg/elgg/engine/lib/views.php:1387<br /> -> [#60] /var/www/elgg/mod/hypeLists/views/default/forms/lists/sort.php:44

**Comment by egbayram** [comment]
WARNING: Deprecated in 2.3: elgg_view_input() is deprecated. Use elgg_view_field() Called from [#56] /var/www/elgg/vendor/elgg/elgg/engine/lib/views.php:1387<br /> -> [#55] /var/www/elgg/mod/hypeInteractions/views/default/forms/comment/save.php:37

**Comment by hypeJunction** [comment]
It's a deprecation warning. It's fine until 3.0
